### ISSUE TITLE
Feature: Ability to provide multiple previews, and switch between them in UI

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#1]
Case one. I have a site that is internationalised. The appearance of a component may change based on the value of a `dir` attribute (i.e. `<html dir="ltr">` or `<html dir="rtl">`).

Case two. I have a site that makes use of some theming.  The appearance of a component may change depending on which class is set on a containing element (i.e. `<body class="t-light">` or `<body class="t-light">`).

In each case, the component’s markup does not change but it’s appearance might, depending on global values. Both for demonstrating and testing that components work when such variables change, it would be nice if you could quickly toggle between them somehow in the UI.

What’s the best way to achieve this? Here’s an initial thought. Currently, components can optionally be rendered within a preview template, so what if multiple preview templates can be defined? Should more than one preview be provided in a components configuration, the UI displays a toggle allowing you to swap between them.

---

Example:

`_preview-ltr.hbs`:

```
<html dir="ltr">
    <head>
        …
    </head>

    <body>
        {{ yield }}
    </body>
</html>
```

`_preview-rtl.hbs`:

```
<html dir="rtl">
    <head>
        …
    </head>

    <body>
        {{ yield }}
    </body>
</html>
```

`component/component.config.yml`:

```
preview:
  - label: "Left to right"
    layout: '_preview-ltr.hbs'
  - label: "Right to left"
    layout: '_preview-rtl.hbs'
```

Am I over thinking this? Can this be achieved another way?

**Comment by allmarkedup** [comment]
Only just seen this as I for some reason wasn't subscribed to notification for this repo :-)

So the best way to achieve this within what is currently possible is to define a couple of variants for the component within the component configuration file (as opposed to as seperate view files). Each variant can specify it's own preview layout and data but (unless specified otherwise) will use the same main component view template.

I'm going to work on the variant documentation shortly but for until that is done the component config reference has an example of how to specify the variants together with what properties they can have set: https://github.com/frctl/fractal/blob/master/docs/components/configuration.md#example-component-configuration-file

Also, to avoid ending up with lots of very similar preview layouts, when a layout is rendered it has access to a special `_target` property that represents the item being rendered within it. So you could set a context property like 'textDirection' in the variant's context and then access it from the preview layout by using `{{ _target.context.textDirection }}`. That way you can have one preview layout that behaves differently depending on the item that it is wrapping. Some docs on the `_target` property here: https://github.com/frctl/fractal/blob/master/docs/components/layouts.md#the-_target-property

**Comment by allmarkedup** [comment]
Closing this as I think variants combined with dynamic layouts address this use case well enough.
