### ISSUE TITLE
Close icon renders incorrectly in Firefox

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#13]
For some reason, Firefox interprets the CSS transforms required to create the cross differently to WebKit/Blink.

WebKit (Safari 9.03): 
![webkit](https://cloud.githubusercontent.com/assets/813383/13906744/10641c22-eed6-11e5-8b4d-642eeecf0935.png)

Gecko (Firefox 47.0): 
![gecko](https://cloud.githubusercontent.com/assets/813383/13906751/2db6547a-eed6-11e5-8ac1-03904ef2ddc8.png)

**Comment by emilbjorklund** [comment]
This is due to Firefox not interpreting `transform-origin` the same way on SVG elements – instead, the origin is always the SVG viewport. [This bug](https://bugzilla.mozilla.org/show_bug.cgi?id=923193) is about this behavior, and it seems to be on it’s way to a fix, if nothing else by supporting the [`transform-box` property](https://drafts.csswg.org/css-transforms/#transform-box) (where the desired behavior can be specified).

Supposedly, one can use a matrix transform with some clever calculations to acheive a cross browser result – I'd love to look into that as a potential first PR for this lovely, lovely project. :-)

**Comment by paulrobertlloyd** [comment]
Ooh, your help would be lovely, @emilbjorklund.

**Comment by emilbjorklund** [comment]
Any tips on dev environment setup, @paulrobertlloyd?

**Comment by allmarkedup** [comment]
Hey @emilbjorklund - great to see you are having a play around! Do you use slack? If so you can DM me your email address and I'll add you to a slack channel that I've set up for Fractal. Then I can help you out with any queries on there. If you don't use slack then we can figure something else out too... :-)

**Comment by emilbjorklund** [comment]
Done!

**Comment by paulrobertlloyd** [comment]
@allmarkedup @emilbjorklund What’s the status of this? Is it okay to pull, or was it still buggy in Chrome?

**Comment by emilbjorklund** [comment]
Still buggy, I think – haven't had time to have another go at it, sadly!

**Comment by allmarkedup** [comment]
Addressed in 1.0 beta.

**Comment by paulrobertlloyd** [comment]
…there’s @allmarkedup, ruining more of my fun :-(
