### ISSUE TITLE
Components and docs folder names should be reflected in theme URL

### ISSUE THREAD

**Issue by paulrobertlloyd** [frctl/mandelbrot#40]
So, here’s a thing. I changed:

```
fractal.docs.set('path', __dirname + '/src/docs');
```

to:

```
fractal.docs.set('path', __dirname + '/src/resources');
```

and expected this to be reflected in the web theme UI, i.e. `./src/resources/conventions/html.md` resolving to `localhost:3000/resources/conventions/html`. Looking more closely, I can see that routes for the three entity types (`assets`, `components` and `docs`) are hardcoded. Should these not default to their respective configured folder names? This behaviour was certainly unexpected.

**Comment by allmarkedup** [comment]
Sorry @paulrobertlloyd, have to disagree with you here. The URLs are not a direct mapping onto the filesystem, nor should they be because that would mean if you renamed your component/docs directories then any hard-coded URLs you may have added would break. This is unavoidable in some cases but here I don't think a direct folder -> URL mapping is the best way to handle it.

If you want a way to customise the first 'url segment' for components/docs/whatever else (via theme config) then that is something separate. By all means open a PR or a feature request, although I am a _little_ wary of ongoing configuration creep at the moment.

**Comment by paulrobertlloyd** [comment]
Hmmm, okay. 😢 But, maybe consider that:
- This behaviour is unexpected; without reading Fractal’s docs, I certainly assumed URLs within the web UI would reflect the underlying folder nomenclature.
- No software is un-opinionated of course, and if the naming of components/docs/assets is something Fractal wished to enforce, then so be it. Except in this case, **this opinion is inconsistent**. While users can redefine the folder nomenclature used at the file system level, and they can also customise the respective labelling in the UI to match, when it comes to URLs, this option is taken away from them.
- Your concerns around persistent URLs are admirable, yet the same problems arise should you rename components, too.
- Finally, removing the hard coded link within the theme’s routing would mean there wouldn’t need to be additional configuration 😇

I rest my case, M’Lord.

**Comment by allmarkedup** [comment]
> This behaviour is unexpected; without reading Fractal’s docs, I certainly assumed URLs within the web UI would reflect the underlying folder nomenclature.

Unexpected by _you_ perhaps... not necessarily unexpected by everyone :-) No one else has brought up this issue yet so I'm surprised that you feel so convinced that it is the way that everyone thinks it should work. I would certainly not have expected this to be the case, otherwise I'd have made it like that!

> No software is un-opinionated of course, and if the naming of components/docs/assets is something Fractal wished to enforce, then so be it. Except in this case, this opinion is inconsistent. While users can redefine the folder nomenclature used at the file system level, and they can also customise the respective labelling in the UI to match, when it comes to URLs, this option is taken away from them.

This is why I offered the option of redefining it via config, rather than folder name. In fact, setting it via the folder name really _would_ be inconsistent, because currently the label and the title for components/docs are set via configuration and are **not** based on the folder name. 

> Your concerns around persistent URLs are admirable, yet the same problems arise should you rename components, too.

Only if you change their handles. You can specify the handle in the config file and then rename/reorganised the folders as you see fit and the links will never change. Also, a component-level change requires only links associated with that specific component to be updated. A folder-level change would require _all_ component links to be updated. 

> Finally, removing the hard coded link within the theme’s routing would mean there wouldn’t need to be additional configuration

Much as I'd like to avoid additional configuration, I'd like to avoid bad design decisions even more. And this one doesn't smell right to me...

In addition, this would be a pretty big breaking change for a lot of people, as they would suddenly find their URLs changed if they updated to the latest version of the theme. Using config options for the same purpose would be backwards-compatible and so could be rolled out as a minor point release if needed.

Sorry Paul, but it's getting thrown out of court. If you really feel the need to customise the URLs then I'll add it to the feature requests but it will be implemented via configuration.

**Comment by paulrobertlloyd** [comment]
> No one else has brought up this issue yet so I'm surprised that you feel so convinced that it is the way that everyone thinks it should work.

I’m just ahead of the curve, I guess. 😉

> In fact, setting it via the folder name really would be inconsistent, because currently the label and the title for components/docs are set via configuration and are **not** based on the folder name.

Okay, I’ll let you have that one. But there’s a level of inconsistency here in terms of _what_ is customisable, that I think could be resolved.

> A folder-level change would require _all_ component links to be updated.

’Tis true.

> …this would be a pretty big breaking change for a lot of people, as they would suddenly find their URLs changed if they updated to the latest version of the theme.

You’re good at this, aren’t you. Still, I call a mistrial, so [I’m taking it to appeal](41)!

(Enjoying your holiday? 😉🏖)
