### ISSUE TITLE
Close All Nested Items on Parent Close

### ISSUE THREAD

**Issue by julkue** [frctl/mandelbrot#67]
In the navigation, if you close a parent navigation item, all children items should be closed too.

**Comment by LeBenLeBen** [comment]
Relates to #78

**Comment by LeBenLeBen** [comment]
As a user, I would not expect this behavior I think.

I worked on other improvement related to this. We won't persist the state beyond user session anymore (#110) and we already added a "collapse all" button (#107) to be shipped with the next release.

I hope those will serve your needs, otherwise please explain why you would need this.
